dist: trusty
language: ruby


sudo: required
services:
  - docker


script: |
  .travis.d/build.sh &&
  cd .travis.d && bundle install --path vendor/bundle &&
  bundle exec ruby pr_autodeploy.rb

env:
  global:
    - HACKGPROJECT_REV="57d0ea9b1854591666337a3fb0853a169330cfa4"

    - DOCKER_ID_USER="hackgt"

