git:
    branch: master

wants:
    mongo: true

health:
  path: /version

secrets:
  - ADMIN_KEY_SECRET
  - SESSION_SECRET
  - EMAIL_KEY
  - GOOGLE_CLIENT_ID
  - GOOGLE_CLIENT_SECRET
  - STORAGE_ENGINE_OPTIONS

env:
  STORAGE_ENGINE: s3
  COOKIE_SECURE_ONLY: true
  EMAIL_FROM: "HackGT Team <hello@hackgt.com>"
  PRODUCTION: true
  ADMIN_EMAILS:
    - stephanie@hack.gt
    - evan@hack.gt
    - claudia@hack.gt
    - catalyst@hack.gt

