git:
    branch: master

wants:
    mongo: true

health:
  path: /version

secrets:
  - ADMIN_KEY_SECRET
  - SESSION_SECRET
  - EMAIL_KEY
  - GROUND_TRUTH_URL
  - GROUND_TRUTH_ID
  - GROUND_TRUTH_SECRET
  - STORAGE_ENGINE_OPTIONS
  - HELPSCOUT_INTEGRATION_SECRET_KEY
  - HELPSCOUT_BEACON_SUPPORT_HISTORY_SECRET_KEY

env:
  STORAGE_ENGINE: gcs
  COOKIE_SECURE_ONLY: true
  EMAIL_FROM: "HackGT Team <hello@hackgt.com>"
  PRODUCTION: true
  ADMIN_EMAILS:
    - stephanie@hack.gt
    - claudia@hack.gt
    - evan@hack.gt

